version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis
    command: ["redis-server", "--bind", "redis"]
    volumes:
          - ./tmp/db:/var/lib/redis/data
    ports:
     - "6350:6379"
#  redis:
#      image: 'redis:4.0-alpine'
#      command: ["redis-server", "--bind", "redis"]
#      volumes:
#        - ./tmp/db:/var/lib/redis/data
#  cable:
#    depends_on:
#      - redis
#    build: .
#    command: puma -p 28080 cable/config.ru
#    ports:
#      - '28080:28080'
#    volumes:
#      - .:/chat-app
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/chat-app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
