version: '3'
volumes:
  postgres_data: {}
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis
    command: ["redis-server", "--bind", "redis"]
    volumes:
          - ./tmp/db:/var/lib/redis/data
    ports:
     - "6350:6379"
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
          - .:/chat-app
    depends_on:
      - db
      - redis
#  web:
#    build: .
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#    volumes:
#      - .:/chat-app
#    ports:
#      - "3000:3000"
#    depends_on:
#      - db
#      - redis
  web:
      build:
        context: .
        dockerfile: ./docker/web/Dockerfile
      depends_on:
        - app
      ports:
        - 8080:80
#  web:
#    build:
#      context: .
#      dockerfile: ./docker/web/Dockerfile
#    ports:
#      - 80:80
#    depends_on:
#      - db
#      - redis
